# Generated by Django 3.1.3 on 2022-02-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220202_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_grade',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
    ]
